# Generated by Django 5.1.1 on 2024-09-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_alter_customer_options_remove_customer_email_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"permissions": [("cancel_order", "Can cancel order")]},
        ),
        migrations.AddField(
            model_name="customer",
            name="phone",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
